//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comentario
    {
        public int Id { get; set; }

        [MinLength(1, ErrorMessage = "Escriba al menos un caracter")]
        public string ComentarioTxt { get; set; }
        public string FechaComentario { get; set; }
        public int UsuarioId { get; set; }
        public int TareaId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
